@host=https://localhost:1234

POST {{hots}}/auth/register
Content-Type: application/json

{
	"firstName":"Michael",
	"lastName":"Rivas",
	"email": "michael.rivas@email.com",
	"password": "123456789!"
}